<a href="https://colab.research.google.com/github/anderson-perez/IAC/blob/main/Exemplo_regress%C3%A3o_log%C3%ADstica_Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
dados = pd.read_csv('/content/diabetes.csv')

In [4]:
dados.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1


In [5]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
dados.isnull().sum()

,0
Pregnancies,0
Glucose,0
BloodPressure,0
SkinThickness,0
Insulin,0
BMI,0
DiabetesPedigreeFunction,0
Age,0
Outcome,0


In [11]:
dados['Outcome'].value_counts()

,count
Outcome,
0,500
1,268


In [12]:
# Separar dados
X = dados.iloc[:, 0:8].values
y = dados.iloc[:, 8].values

In [13]:
X.shape

(768, 8)

In [14]:
y.shape

(768,)

In [15]:
from sklearn.model_selection import train_test_split

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, random_state=7)

In [16]:
X_treino.shape, y_treino.shape

((576, 8), (576,))

In [17]:
from sklearn.linear_model import LogisticRegression

In [26]:
log = LogisticRegression(max_iter=2000)

In [27]:
log.fit(X_treino, y_treino)

LogisticRegression(max_iter=2000)

In [28]:
y_pred = log.predict(X_teste)

In [29]:
y_pred == y_teste

array([ True,  True,  True,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,

In [30]:
# Usar o modelo
y_teste[0]

np.int64(0)

In [31]:
log.predict([X_teste[0]])

array([0])

In [32]:
log.coef_

array([[ 0.13071346,  0.03286527, -0.01497749,  0.00445297, -0.00135773,
         0.09549576,  1.10922172,  0.01324811]])

In [33]:
log.intercept_

array([-8.33247872])

In [34]:
log.classes_

array([0, 1])

In [42]:
log.decision_function(X_treino)

(576,)

In [43]:
log.score(X_teste, y_teste)

0.7760416666666666